### ISSUE TITLE
Could you provide an English version of the paper?

### ISSUE THREAD

**Issue by thuhuwei** [Bkmz21/FD-Evaluation#2]
The Abstract is very attractive, but I can't understand the content written in Russian. Is it possible to provide an English version? Thanks.

**Comment by Bkmz21** [comment]
Hi. Unfortunately, there is no english translation. Translate paper in English will be available in a few months.

About general idea you can read in this paper http://personal.stevens.edu/~hli18/papers/CVPR2015_CasCNN.pdf

We have considered a subproblem of frontal and half-frontal face detection.
Our work has several differences:
1) Used very small CNN (stage1 - 797, stage2 - 1819, stage3 - 2923 parameters). But they have enough discriminant power for obtaining a high recall (see figure 9). The first stage of our cascade, even with a zero threshold (max 1.7) have a small number of false alarms (see table 9).
2) Using YouTube Faces Database (grayscale) instead AFLW (color) for training.
3) Calibration CNN is not used, instead of them parts of faces were added to the training set.
4) Our detector has a more complex pipeline necessary to effectively rejecting false alarms.
5) Significant amount of research and development effort has been spent on the optimization of the detector (see figure 11 and 12).

Note. Comparison was made only with the frontal face detectors (except FDPL) for which the source codes or demo versions are publicly available. The uniform method of evaluation for each database was used (not default method for FDDB). Multi-view face detectors capable of providing higher recall and precision but not real-time.The search for a compromise between the precision and speed processing was the purpose of this work.

**Comment by thuhuwei** [comment]
Thanks!

**Comment by futurely** [comment]
https://translate.google.com

**Comment by Bkmz21** [comment]
English version available http://arxiv.org/abs/1508.01292.
